import "./globals.css";
import type { Metadata } from "next";
import { Cabin, Luckiest_Guy, Bebas_Neue } from "next/font/google";
import Header from "./Header";

const cabin = Cabin({ subsets: ["latin"], variable: "--font-cabin" });
const luckiestGuy = Luckiest_Guy({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-luckiest-guy",
});
const bebasNeue = Bebas_Neue({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bebas-neue",
});

export const metadata: Metadata = {
  title: "Nouns Esports",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth overflow-x-hidden">
      <body
        className={`cursor-crosshair ${cabin.variable} ${luckiestGuy.variable} ${bebasNeue.variable} bg-black text-lightgrey font-cabin selection:text-white selection:bg-red`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
