import { Talent } from "@/db/schema";

export default async function fetchTalents(ids?: string[]) {
  const talents: Talent[] = [
    {
        id: "pekka",
        active: true,
        name: "Pekka",
        image: "/talent/brawl-stars/pekka.webp",
        role: "Player",
        roster: "brawl-stars",
        liquipedia: "https://liquipedia.net/brawlstars/Pekka",
        twitch: null,
        twitter: "https://twitter.com/PekkaBS2",
        youtube: null,
        tiktok: null,
        instagram: "https://www.instagram.com/pekkabs2/",
      },
      {
        id: "firecrow",
        active: true,
        name: "FireCrow",
        image: "/talent/brawl-stars/firecrow.webp",
        role: "Player",
        roster: "brawl-stars",
        liquipedia: "https://liquipedia.net/brawlstars/FireCrow",
        twitch: "https://www.twitch.tv/zfirecrow",
        twitter: "https://twitter.com/FireCrowBS",
        youtube: "https://www.youtube.com/FireCrowBrawlStars",
        tiktok: null,
        instagram: "https://www.instagram.com/lucca_firecrow/",
      },
      {
        id: "mohtep",
        active: true,
        name: "Mohtep",
        image: "/talent/brawl-stars/mohtep.webp",
        role: "Player",
        roster: "brawl-stars",
        liquipedia: "https://liquipedia.net/brawlstars/Mohtep",
        twitch: "https://www.twitch.tv/Mohtepbs",
        twitter: "https://twitter.com/Mohtepbs",
        youtube: null,
        tiktok: "https://www.tiktok.com/@Mohtepbs",
        instagram: null,
      },
      {
        id: "rol",
        active: true,
        name: "Rol",
        image: "/talent/brawl-stars/rol.webp",
        role: "Coach",
        roster: "brawl-stars",
        liquipedia: "https://liquipedia.net/brawlstars/Rol",
        twitch: "https://www.twitch.tv/rol_09",
        twitter: "https://twitter.com/Rol09_BS",
        youtube: "https://www.youtube.com/channel/UCm6TBGI0IKmOlrOoNyiBP5A",
        tiktok: null,
        instagram: "https://www.instagram.com/rol_bs/",
      },
      {
        id: "quinaia",
        active: true,
        name: "Quinaia",
        image: "/talent/brawl-stars/quinaia",
        role: "Analyst",
        roster: "brawl-stars",
        liquipedia: "https://liquipedia.net/brawlstars/Quinaia",
        twitch: "https://www.twitch.tv/quinaiagg",
        twitter: "https://twitter.com/Quinaiagg",
        youtube: null,
        tiktok: null,
        instagram: "https://www.instagram.com/leo_quinaia/",
      },
      {
        id: "cynic",
        active: true,
        name: "Cynic",
        image: "/talent/csgo/cynic.webp",
        role: "Awper",
        roster: "csgo",
        liquipedia: "https://liquipedia.net/counterstrike/Cynic",
        twitch: null,
        twitter: "https://twitter.com/cyn1c_fps",
        youtube: null,
        tiktok: null,
        instagram: null,
      },
      {
        id: "nosrac",
        active: true,
        name: "nosraC",
        image: "/talent/csgo/nosrac.webp",
        role: "IGL",
        roster: "csgo",
        liquipedia: "https://liquipedia.net/counterstrike/NosraC",
        twitch: "https://www.twitch.tv/nosrac_",
        twitter: "https://twitter.com/nosraC_cs",
        youtube: null,
        tiktok: null,
        instagram: null,
      },
      {
        id: "marke",
        active: true,
        name: "MarKE",
        image: "/talent/csgo/marke.webp",
        role: "Player",
        roster: "csgo",
        liquipedia: "https://liquipedia.net/counterstrike/MarKE",
        twitch: "https://www.twitch.tv/marke_1",
        twitter: "https://twitter.com/MarkeCSGO",
        youtube: null,
        tiktok: null,
        instagram: null,
      },
      {
        id: "semphis",
        active: true,
        name: "Semphis",
        image: "/talent/csgo/semphis.webp",
        role: "Coach",
        roster: "csgo",
        liquipedia: "https://liquipedia.net/counterstrike/SEMPHIS",
        twitch: "https://www.twitch.tv/semphis",
        twitter: "https://twitter.com/semphisss",
        youtube: null,
        tiktok: null,
        instagram: null,
      },
      {
        id: "cj",
        active: true,
        name: "cJ",
        image: "/talent/csgo/cj.webp",
        role: "Rifler",
        roster: "csgo",
        liquipedia: "https://liquipedia.net/counterstrike/CJ",
        twitch: "https://www.twitch.tv/cjdak1ng",
        twitter: "https://twitter.com/cJdAK1nG",
        youtube: null,
        tiktok: null,
        instagram: null,
      },
      {
        id: "bwills",
        active: true,
        name: "Bwills",
        image: "/talent/csgo/bwills.webp",
        role: "Rifler",
        roster: "csgo",
        liquipedia: "https://liquipedia.net/counterstrike/Bwills",
        twitch: "https://www.twitch.tv/bwills4",
        twitter: "https://twitter.com/bwillsCSGO",
        youtube: null,
        tiktok: null,
        instagram: null,
      },
      {
        id: "astini",
        active: true,
        name: "Astini",
        image: "/talent/dota-2/astini.webp",
        role: "Coach",
        roster: "dota-2",
        liquipedia: "https://liquipedia.net/dota2/Astini",
        twitch: "https://www.twitch.tv/filipeastini",
        twitter: "https://twitter.com/filipeastini",
        youtube: "https://www.youtube.com/filipeastini",
        tiktok: null,
        instagram: "https://www.instagram.com/filipeastini/",
      },
      {
        id: "lelis",
        active: true,
        name: "Lelis",
        image: "/talent/dota-2/lelis.webp",
        role: "Soft Support",
        roster: "dota-2",
        liquipedia: "https://liquipedia.net/dota2/LESL%C3%83O",
        twitch: "https://www.twitch.tv/lelisdota",
        twitter: "https://twitter.com/lelisdota",
        youtube: "https://www.youtube.com/c/Lelisdota",
        tiktok: null,
        instagram: "https://www.instagram.com/lelisdota/",
      },
      {
        id: "gunnar",
        active: true,
        name: "Gunnar",
        image: "/talent/dota-2/gunnar.webp",
        role: "Midlane",
        roster: "dota-2",
        liquipedia: "https://liquipedia.net/dota2/Gunnar",
        twitch: "https://www.twitch.tv/gunnardota2",
        twitter: "https://twitter.com/gunnardota",
        youtube: "https://www.youtube.com/c/GunnarDota/featured",
        tiktok: null,
        instagram: null,
      },
      {
        id: "fly",
        active: true,
        name: "Fly",
        image: "/talent/dota-2/fly.webp",
        role: "Player",
        roster: "dota-2",
        liquipedia: "https://liquipedia.net/dota2/Fly",
        twitch: "https://www.twitch.tv/talflyaizik",
        twitter: "https://twitter.com/talflyaizik",
        youtube: null,
        tiktok: null,
        instagram: "https://www.instagram.com/talflyaizik/",
      },
      {
        id: "stormstormer",
        active: true,
        name: "Stormstormer",
        image: "/talent/dota-2/stormstormer.webp",
        role: "Player",
        roster: "dota-2",
        liquipedia: "https://liquipedia.net/dota2/Stormstormer",
        twitch: "https://www.twitch.tv/stormstormer",
        twitter: "https://twitter.com/StormingStorm",
        youtube: null,
        tiktok: null,
        instagram: "https://www.instagram.com/stormingstorm_dota/",
      },
      {
        id: "yuma",
        active: true,
        name: "Yuma",
        image: "/talent/dota-2/yuma.webp",
        role: "Player",
        roster: "dota-2",
        liquipedia: "https://liquipedia.net/dota2/Yuma",
        twitch: "https://www.twitch.tv/yumalm",
        twitter: "https://twitter.com/yumadota",
        youtube: null,
        tiktok: null,
        instagram: null,
      },
      {
        id: "xblaine",
        active: true,
        name: "xBlaine",
        image: "/talent/pokemon-unite/xblaine.webp",
        role: "Coach",
        roster: "pokemon-unite",
        liquipedia: "https://liquipedia.net/pokemon/XBlaine",
        twitch: "https://www.twitch.tv/xblainehs",
        twitter: "https://twitter.com/xBlaineHS",
        youtube: null,
        tiktok: null,
        instagram: null,
      },
      {
        id: "adesu",
        active: true,
        name: "Adesu",
        image: "/talent/pokemon-unite/adesu.webp",
        role: "Jungle",
        roster: "pokemon-unite",
        liquipedia: "https://liquipedia.net/pokemon/ADESu",
        twitch: "https://www.twitch.tv/adesu23",
        twitter: "https://twitter.com/ADESuUnite",
        youtube: "https://www.youtube.com/channel/UCUDtwo4nesTY1DlkwS7TifQ",
        tiktok: null,
        instagram: null,
      },
      {
        id: "megumini",
        active: true,
        name: "Megumini",
        image: "/talent/pokemon-unite/megumini.webp",
        role: "Player",
        roster: "pokemon-unite",
        liquipedia: "https://liquipedia.net/pokemon/Megumini",
        twitch: null,
        twitter: "https://twitter.com/Megumini_",
        youtube: null,
        tiktok: null,
        instagram: null,
      },
      {
        id: "yutao",
        active: true,
        name: "Yûtao",
        image: "/talent/pokemon-unite/yutao.webp",
        role: "Player",
        roster: "pokemon-unite",
        liquipedia: "https://liquipedia.net/pokemon/Yutao",
        twitch: "https://www.twitch.tv/YutaoUnite",
        twitter: "https://twitter.com/YutaoUnite",
        youtube: null,
        tiktok: null,
        instagram: null,
      },
      {
        id: "toonslim",
        active: true,
        name: "ToonSlim",
        image: "/talent/pokemon-unite/toonslim.webp",
        role: "Player",
        roster: "pokemon-unite",
        liquipedia: "https://liquipedia.net/pokemon/ToonSlim",
        twitch: null,
        twitter: "https://twitter.com/Toon_Slim",
        youtube: null,
        tiktok: null,
        instagram: null,
      },
      {
        id: "bruv",
        active: true,
        name: "Bruv",
        image: "/talent/pokemon-unite/bruv.webp",
        role: "Tank",
        roster: "pokemon-unite",
        liquipedia: "https://liquipedia.net/pokemon/Bruv",
        twitch: "https://www.twitch.tv/bruvhd",
        twitter: "https://twitter.com/BruvHD",
        youtube:
          "https://www.youtube.com/channel/UC2SQYCvfzZswQNQp0n8UAPA/videos",
        tiktok: null,
        instagram: null,
      },
      {
        id: "aklo",
        active: true,
        name: "Aklo",
        image: "/talent/smash-melee/aklo.webp",
        role: "Fox / Link",
        roster: "smash-melee",
        liquipedia: "https://liquipedia.net/smash/Aklo",
        twitch: "https://www.twitch.tv/Aklo214",
        twitter: "https://twitter.com/NotAklo",
        youtube: "https://www.youtube.com/@Aklossbm",
        tiktok: "https://www.tiktok.com/@notaklo",
        instagram: null,
      },
  ];

  if (ids) {
    return talents.filter((talent) => ids.includes(talent.id));
  }

  return talents;
}